version: "3.8"
services:
  # neo4j:
  #   image: neo4j:5.26-community
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     NEO4J_AUTH: neo4j/password123
  #     NEO4J_PLUGINS: '["apoc"]'
  #   volumes:
  #     - neo4j_data:/data

  graphiti:
    image: zepai/graphiti:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}

volumes:
  neo4j_data:
